var generators={
	'amk':{
		'title': 'Adventures in the Magic Kingdom',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"999 ghosts are in this\n\nhouse. but they're always\n\nlooking for number 1,000.\n\nBe careful--They might\n\nwant you!\n             \u25bc",
		'added':'2018-08-26',
		'year': 1990,
		'platform':'nes',
		'gameinfo':'https://www.mobygames.com/game/disney-adventures-in-the-magic-kingdom'
	},
	'af2':{
		'title': 'Aero Fighters 2',
		'source':'Video System',
		'sourceurl':'https://en.wikipedia.org/wiki/Aero_Fighters',
		'defaulttext':"I am the world's first\ndolphin pilot.",
		'added':'2018-05-06',
		'platform':'arcade',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/aero-fighters-2',
		'series':'aero fighters'
	},
	'aba':{
		'title': 'All About America',
		'source':'Unicorn Software',
		'sourceurl':'https://www.mobygames.com/company/unicorn-software-company',
		'defaulttext':"  Many, many years ago\na Spanish sailor named\nChristopher Columbus\nwanted to find a\nshorter way to get to\nthe East Indies.  The",
		'added':'2019-07-29',
		'platform':'apple2',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/apple2/all-about-america',
		'play':'https://archive.org/details/AllAboutAmerica4amCrack'
	},
	'aitd':{
		'title': 'Alone in the Dark',
		'source':'Infogrames',
		'sourceurl':'https://en.wikipedia.org/wiki/Infogrames',
		'defaulttext':"Artemis guide us as though we were an \narrow from her quiver.\"",
		'added':'2020-06-11',
		'platform':'dos',
		'year':1992,
		'series':'alone in the dark',
		'gameinfo':'https://archive.org/details/msdos_Alone_in_the_Dark_1992',
	},
	'ag':{
		'title': 'American Gladiators',
		'source':'Incredible Technologies, inc.',
		'sourceurl':'https://en.wikipedia.org/wiki/Incredible_Technologies',
		'defaulttext':"\"To hit and not be hit, That\nis the answer.\" ",
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/nes/american-gladiators',
		'platform':'nes',
		'added':'2018-10-29'
	},
	'ancients':{
		'title': 'Ancients',
		'source':'Farr-Ware Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Ancients_1:_Death_Watch',
		'defaulttext':"You have never felt the\nneed to recall the\nmemories of your youth.\nThe dreams that have\nhaunted you these last\nnights act as a reminder\nof where you came from\nand what you have seen.\n\nPlaying in the fields\nare among the strongest\nmemories of your youth.\nthere you spent much \ntime exploring, playing\nthe role  of  a  wild",
		'play':"https://archive.org/details/msdos_Ancients_1_Deathwatch",
		'year':1991,
		'added':'2018-04-16',
		'gameinfo':'https://www.mobygames.com/game/ancients-1-death-watch',
		'platform':'dos'
	},
	'acww':{
		'title':'Animal Crossing: Wild World',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':'Tom Nook\nAllow me an introduction.\nMy name is [pink]Tom Nook[/], and I\nown the store in this town.',
		'year':2005,
		'platform':'ds',
		'added':'2019-02-20',
		'gameinfo':'https://www.mobygames.com/game/nintendo-ds/animal-crossing-wild-world',
		'series':'animal crossing'
	},
	'aof1':{
		'title':'Art of Fighting',
		'source':'SNK',
		'sourceurl':'https://en.wikipedia.org/wiki/SNK',
		'defaulttext':"Now you understand.\nDon't judge me by my looks.",
		'year':1992,
		'platform':'arcade',
		'added':'2020-03-23',
		'gameinfo':'https://www.mobygames.com/game/art-of-fighting',
		'series':'art of fighting'
	},
	'atari8bit':{
		'title':'Atari 8-bit',
		'source':'Atari, Inc.',
		'sourceurl':'https://en.wikipedia.org/wiki/Atari,_Inc.',
		'defaulttext':'READY\n[inverse] [/inverse]',
		'year':1979,
		'platform':'atari8bit',
		'added':'2019-06-12',
		'gameinfo':'https://en.wikipedia.org/wiki/Atari_8-bit_family',
	},
	'baddudes':{
		'title': 'Bad Dudes',
		'source':'Data East',
		'sourceurl':'https://en.wikipedia.org/wiki/Data_East',
		'defaulttext':" The president has been\n\nkidnapped by Ninjas.\n\n\n Are you a bad enough dude\n\nto rescue the president?",
		'content-type':'Trump edit',
		'content-contributor': 'Dustin Gunn',
		'content-contributor-url': 'https://twitter.com/dustin_gunn',
		'platform':'nes',
		'gameinfo':'https://www.mobygames.com/game/nes/bad-dudes',
		'year':1989,
		'added':'2018-03-30',
		'updated':'2019-01-15'
	},
	'battletoads':{
		'title': 'Battletoads',
		'source':'Rare',
		'sourceurl':'https://en.wikipedia.org/wiki/Rare_(company)',
		'defaulttext':"So, the rat rockets didn't\n\nget you, huh? Well, the\n\nice spikes certainly will!",
		'platform':'nes',
		'gameinfo':'https://www.mobygames.com/game/battletoads',
		'year':1991,
		'added':'2020-08-13',
		'series':'battletoads'
	},
	'bsd':{
		'title': 'Bishoujo Sexy Derby',
		'source':'Super Pig',
		'sourceurl':'https://en.wikipedia.org/wiki/Hacker_International#Super_Pig_games',
		'defaulttext':"You idiot! Can't\n you do better?",
		'content-type':'Translation',
		'content-contributor': 'Spinner 8',
		'content-contributor-url': 'https://www.romhacking.net/translations/7',
		'platform':'nes',
		'year':1988,
		'gameinfo':'https://www.romhacking.net/translations/7/',
		'added':'2019-03-13'
	},
	'bt':{
		'title': 'Blackthorne',
		'source':'Blizzard',
		'sourceurl':'https://en.wikipedia.org/wiki/Blizzard_Entertainment',
		'defaulttext':"I AM GOING TO\nCRUSH YOU AND\nSPIT ON YOUR\nBONES, BOY!",
		'platform':'snes',
		'year':1994,
		'play':'https://archive.org/details/blackthorne_2013',
		'gameinfo':'https://www.mobygames.com/game/blackthorne',
		'added':'2018-12-26'
	},
	'blade':{
		'title': 'Blade',
		'source':'HAL Laboratory & Avit Inc',
		'sourceurl':'https://en.wikipedia.org/wiki/HAL_Laboratory',
		'defaulttext':"COME ON OUT, MONSTER!",
		'platform':'gameboy',
		'year':2000,
		'gameinfo':'https://www.mobygames.com/game/blade__',
		'added':'2020-08-16'
	},
	'bsod':{
		'title': 'BSOD',
		'source':'Microsoft',
		'sourceurl':'https://en.wikipedia.org/wiki/Microsoft',
		'defaulttext':"[inverse] Windows [/]\n\nA fatal exception 0E has occurred at 0028:C002ADB7 in VXD VFAT(01) +\n0000A3D7. The current application will be terminated.\n\n*  Press any key to terminate the current application.\n*  Press CTRL+ALT+DEL again to restart your computer. You will\n   lose any unsaved information in all applications.\n\n                      Press any key to continue ",
		'platform':'win32',
		'year':1995,
		'gameinfo':'https://en.wikipedia.org/wiki/Windows_95',
		'added':'2019-03-10'
	},
	'billnted':{
		'title': 'Bill & Ted',
		'source':'Rocket Science Games',
		'sourceurl':'https://en.wikipedia.org/wiki/Rocket_Science_Games',
		'defaulttext':'Ask the locals for\nhelp, but remember\nto be excellent to\neveryone... Don\'t\nmake them mad!',
		'platform':'nes',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/nes/bill-teds-excellent-video-game-adventure',
		'added':'2019-02-10'
	},
	'bm':{
		'title': 'Bio Menace',
		'source':'Apogee Software',
		'sourceurl':'https://en.wikipedia.org/wiki/3D_Realms',
		'defaulttext':"  Somewhere in each level, there\nis someone like me who holds a key\nto each exit.  You must find them!",
		"play":"https://archive.org/details/BioMenace",
		'platform':'dos',
		'gameinfo':'https://www.mobygames.com/game/bio-menace',
		'year':1993,
		'added':'2018-01-12'
	},
	'bc':{
		'title': 'Bionic Commando',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"GET THE HECK OUT\nOF HERE, YOU\nNERD!",
		'platform':'nes',
		'added':'2018-10-21',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/bionic-commando_'
	},
	'bl':{
		'title': 'Brain Lord',
		'source':'Enix',
		'sourceurl':'https://en.wikipedia.org/wiki/Enix',
		'defaulttext':"Welcome to Toronto.\nThis is your first\nvisit, isn't it?",
		'platform':'snes',
		'added':'2020-06-15',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/brain-lord'
	},
	'bof4':{
		'title': 'Breath of Fire IV',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"\"Whoa! Look at the\n size of that hole!\"",
		'platform':'ps1',
		'added':'2019-02-13',
		'year':2000,
		'gameinfo':'https://www.mobygames.com/game/breath-of-fire-iv',
		'series':'breath of fire'
	},
	'codaw':{
		'title': 'Call of Duty: Advanced Warfare',
		'source':'Sledgehammer Games',
		'sourceurl':'https://en.wikipedia.org/wiki/Sledgehammer_Games',
		'defaulttext':'Press [yellow]F[/] to Pay Respects',
		'added':'2021-01-28',
		'platform':'win32',
		'gameinfo':'https://www.mobygames.com/game/call-of-duty-advanced-warfare',
		'year':2014
	},
	'cn':{
		'title': 'Captain Novolin',
		'source':'Sculptured Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Sculptured_Software',
		'defaulttext':'You need to check your\nblood sugar four times a \nday,but you can check it \n more often if you like.',
		'added':'2018-05-13',
		'platform':'snes',
		'gameinfo':'https://www.mobygames.com/game/snes/captain-novolin',
		'year':1992
	},
	'cpap':{
		'title': 'Captain Planet',
		'source':'Chris Gray Enterprises',
		'sourceurl':'https://www.mobygames.com/company/chris-gray-enterprises-inc',
		'defaulttext':'The Earth is dying, Planeteers.',
		'year':1991,
		'platform':'nes',
		'added':'2019-01-26',
		'gameinfo':'https://www.mobygames.com/game/captain-planet-and-the-planeteers_'
	},
	'carma':{
		'title': 'Carmageddon',
		'source':'Stainless Games',
		'sourceurl':'https://en.wikipedia.org/wiki/Stainless_Games',
		'defaulttext':'[white]Screwie[/]\nHave you got\nthe guts to\ntrade places,\nPunk?',
		'play':"https://archive.org/details/msdos_Carmageddon_Max_Pack_1998",
		'added':'2018-05-21',
		'year':1997,
		'gameinfo':'https://www.mobygames.com/game/dos/carmageddon',
		'platform':'dos',
		'series':'carmageddon'
	},
	'cotw':{
		'title': 'Castle of the Winds',
		'source':'SaadaSoft',
		'sourceurl':'https://en.wikipedia.org/wiki/Castle_of_the_Winds',
		'defaulttext':'John Doe\nDied\n5-31-2018\n[small]Killed by a Kobold[/small]',
		'play':"https://archive.org/details/win3_CasWin1",
		'gameinfo':'https://www.mobygames.com/game/win3x/castle-of-the-winds',
		'year':1993,
		'platform':'win16',
		'added':'2018-05-31'
	},
	'cv2':{
		'title': 'Castlevania II',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':'What a\nhorrible\nnight to\nhave a\ncurse.',
		'platform':'nes',
		'added':'2018-04-28',
		'updated':'2020-04-20',
		'series':'castlevania',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/castlevania-ii-simons-quest'
	},
	'cl':{
		'title': 'Castlevania Legends',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':'\nCount\n\nDracula\n\nget away',
		'platform':'gameboy',
		'added':'2018-10-27',
		'series':'castlevania',
		'year':1998,
		'gameinfo':'https://www.mobygames.com/game/gameboy/castlevania-legends'
	},
	'sotn':{
		'title': 'Castlevania Symphony of the Night',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':'Dracula\nWhat is a man?\nA miserable little pile of secrets.',
		'contributions':[
			{
				'type':'christmas theme',
				'contributor': '@Ashuraou',
				'url': 'https://twitter.com/ashuraou'
			},
			{
				'type':'Bernie Sanders theme',
				'contributor': 'A_Rival, aka DJ iPad',
				'url': 'https://twitter.com/8bitpimp'
			}
		],
		'platform':'ps1',
		'added':'2018-02-23',
		'updated':'2021-02-09',
		'series':'castlevania',
		'gameinfo':'https://www.mobygames.com/game/castlevania-symphony-of-the-night',
		'year':1997
	},
	'cs':{
		'title': 'Cave Story+',
		'source':'Pixel',
		'sourceurl':'https://en.wikipedia.org/wiki/Daisuke_Amaya',
		'defaulttext':"Oh, sorry 'bout that.\nThe Doctor's such a cruel\nand evil person.",
		'platform':'win32',
		'added':'2018-04-12',
		'year':2005,
		'gameinfo':'https://www.mobygames.com/game/cave-story'
	},
	'a52cm':{
		'title': 'The Cheetahmen',
		'source':'Active Enterprises',
		'sourceurl':'https://en.wikipedia.org/wiki/Action_52',
		'defaulttext':"The Action Gamemaster was at\nhome playing his video game.\nWhen suddenly...",
		"year": 1991,
		"platform":"nes",
		"added":"2018-11-18",
		'gameinfo':'https://www.mobygames.com/game/action-52'
	},
	'ct':{
		'title': 'Chrono Trigger',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"FLEA: Male\u2026female\u2026\u2026what's the\n   difference?\n   Power is beautiful, and I've got the\n   power!",
		'added':'2019-02-21',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/chrono-trigger',
		'platform':'snes',
		'series':'chrono trigger'
	},
	'citycon':{
		'title': 'City Connection',
		'source':'Jaleco',
		'sourceurl':'https://en.wikipedia.org/wiki/Jaleco',
		'defaulttext':"Now, you have driven\n\n all the highway !!\n\n\n \uD83D\uDEE2 OIL  3*100=  300",
		'added':'2020-07-15',
		'year':1985,
		'gameinfo':'https://www.mobygames.com/game/arcade/cruisin',
		'platform':'arcade',
	},
	'caption':{
		'title': 'Closed Captions',
		'source':'FCC',
		'sourceurl':'https://en.wikipedia.org/wiki/Federal_Communications_Commission',
		'defaulttext':"\n PUT SPACES BEFORE EACH LINE \n AND AFTER FOR BETTER LOOK ",
		'added':'2018-05-10',
		'platform':'tv',
		'year':1973,
		'gameinfo':'https://en.wikipedia.org/wiki/Closed_captioning'
	},
	'ci':{
		'title': 'Codename: ICEMAN',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"You've overestimated your strength\n and can't thread water any longer.",
		'play':"https://archive.org/details/msdos_Codename_ICEMAN_1989",
		'platform':'dos',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/code-name-iceman',
		'added':'2018-04-15',
	},
	'lb1':{
		'title': 'The Colonel\'s Bequest',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'It\'s not a pretty sight',
		'play':"https://archive.org/details/msdos_Laura_Bow_1_-_The_Colonels_Bequest_1989",
		'platform':'dos',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/colonels-bequest',
		'added':'2018-04-25',
		'series':'laura bow',
	},
	'keen4':{
		'title': 'Commander Keen 4',
		'source':'id Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Id_Software',
		'defaulttext':'Keen enters the\n     Shadowlands',
		'play':"https://archive.org/details/msdos_Commander_Keen_4_-_Secret_of_the_Oracle_1991",
		'platform':'dos',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/commander-keen-goodbye-galaxy',
		'added':'2017-12-19',
		'series':'commander keen'
	},
	'c64':{
		'title': 'Commodore 64',
		'source':'Commodore International',
		'sourceurl':'https://en.wikipedia.org/wiki/Commodore_International',
		'defaulttext':'\n    **** COMMODORE 64 BASIC V2 ****\n\n 64K RAM SYSTEM  38911 BASIC BYTES FREE\n\nREADY.\n[inverse] [/inverse]',
		'play':"https://archive.org/details/c64_basic",
		'platform':'c64',
		'year':1982,
		'gameinfo':'https://en.wikipedia.org/wiki/Commodore_64',
		'added':'2019-06-11',
		'how-to-use':'Emulate this console'
	},
	'chc':{
		'title': 'Contra: Hard Corps',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"THAT'S NOT THE UNMANNED ROBOT!\n\nSOMEBODY IS INSIDE THAT THING!",
		'platform':'genesis',
		'year':1994,
		'series':'contra',
		'gameinfo':'https://www.mobygames.com/game/contra-hard-corps',
		'added':'2020-03-14'
	},
	'cosmo':{
		'title': 'Cosmo\'s Cosmic Adventure',
		'source':'Apogee Software',
		'sourceurl':'https://en.wikipedia.org/wiki/3D_Realms',
		'defaulttext':'       COSMIC HINT!\n\n These hint globes will\n help you along your\n journey.  Press the up\n key to reread them.\n\n Press SPACE to hurry or\n  Press any key to exit.',
		'play':"https://archive.org/details/CosmosCosmicAdventure",
		'platform':'dos',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/cosmos-cosmic-adventure',
		'added':'2018-04-22',

	},
	'crowtel':{
		'title': 'Crowtel Renovations',
		'source':'Sink',
		'sourceurl':'https://twitter.com/sinksadventure',
		'defaulttext':"Someone clogged my\ntoilet. It wasn't me...",
		'platform':'win32',
		'year':2017,
		'gameinfo':'https://store.steampowered.com/app/573520/Crowtel_Renovations/',
		'added':'2018-04-12',

	},
	'centy':{
		'title': 'Crusader of Centy',
		'source':'Nextech',
		'sourceurl':'https://en.wikipedia.org/wiki/Nex_Entertainment',
		'defaulttext':'Tapir:"I am Tapir.\nThe Camelia Desert is\nfilled with sad dreams."',
		'platform':'genesis',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/crusader-of-centy',
		'added':'2019-04-02',
	},
	'darius':{
		'title': 'Darius',
		'source':'Taito',
		'sourceurl':'https://en.wikipedia.org/wiki/Taito',
		'defaulttext':"      [big]WARNING![/]\n\n\n     A huge battleship\n \n       [red]King Fossil-A[/]\n\n    Is approaching fast.\n",
		'platform':'arcade',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/arcade/darius',
		'added':'2018-10-23',

	},
	'dejavu':{
		'title': 'Deja Vu',
		'source':'ICOM Simulations',
		'sourceurl':'https://en.wikipedia.org/wiki/ICOM_Simulations',
		'defaulttext':"Somebody had better look\nout",
		'year': 1988,
		'platform':'nes',
		'added':'2019-01-05',
		'gameinfo':'https://www.mobygames.com/game/nes/deja-vu-a-nightmare-comes-true'
	},
	'deusex':{
		'title': 'Deus Ex',
		'source':'Ion Storm',
		'sourceurl':'https://en.wikipedia.org/wiki/Ion_Storm',
		'defaulttext':"NSF everywhere, JC.  Your orders are to shoot on sight.  A UNATCO informant on the North Dock can get you inside the statue.  Look for a Bum.  Identify yourself with the phrase 'Iron and Copper.'",
		'platform':'win32',
		'year':2000,
		'gameinfo':'https://www.mobygames.com/game/deus-ex',
		'added':'2018-04-17',
		'series':'deus ex'

	},
	'ddp':{
		'title': 'DoDonPachi',
		'source':'CAVE',
		'sourceurl':'https://en.wikipedia.org/wiki/Cave_(company)',
		'defaulttext':"          [red]warning[/red]\n\nthis game is for use in\n[red]JAPAN ONLY.[/red]\nSales, export or operation\noutside this country may be\nconstrued as copyright and \ntrademark infringement and \nis strictly prohibited.\nviolator and subject to\nsevere penalties and will\nbe prosecutedt to the full\nextent of the jam.\n\n[blue]©atlus/cave 1995 1996 1997\n    all rights reserved[/blue]\n    [red]1997 2/5 master ver.[/red]",
		'platform':'arcade',
		'year':1997,
		'gameinfo':'https://www.mobygames.com/game/dodonpachi',
		'added':'2018-05-12',

	},
	'doom':{
		'title': 'Doom',
		'source':'id Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Id_Software',
		'defaulttext':"ONCE YOU BEAT THE BIG BADASSES AND\nCLEAN OUT THE MOON BASE YOU'RE SUPPOSED\nTO WIN, AREN'T YOU? AREN'T YOU? WHERE'S\nYOUR FAT REWARD AND TICKET HOME? WHAT\nTHE HELL IS THIS? IT'S NOT SUPPOSED TO\nEND THIS WAY!\n\nIT STINKS LIKE ROTTEN MEAT, BUT LOOKS\nLIKE THE LOST DEIMOS BASE. LOOKS LIKE\nYOU'RE STUCK ON THE SHORES OF HELL.\nTHE ONLY WAY OUT IS THROUGH.\n\nTO CONTINUE THE DOOM EXPERIENCE, PLAY\nTHE SHORES OF HELL AND ITS AMAZING\nSEQUEL, INFERNO!",
		'play':"https://archive.org/details/DoomsharewareEpisode",
		'platform':'dos',
		'updated':'2019-01-10',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/doom',
		'added':'2018-04-10',
		'series':'doom'

	},
	'dos':{
		'title': 'MS-DOS',
		'source':'Microsoft',
		'sourceurl':'https://en.wikipedia.org/wiki/Microsoft',
		'defaulttext':"Starting MS-DOS...\n\n\nHIMEM is testing extended memory...done.\nC:\\>",
		'platform':'dos',
		'year':1981,
		'gameinfo':'https://en.wikipedia.org/wiki/DOS',
		'added':'2018-05-05',

	},
	'ddv':{
		'title': 'Double Dragon V',
		'source':'Leland Interactive Media',
		'sourceurl':'https://en.wikipedia.org/wiki/Leland_Interactive_Media',
		'defaulttext':"Remember, inside every\nliving person is a dead one\ntrying to get out!",
		'platform':'snes',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/double-dragon-v-the-shadow-falls',
		'added':'2019-04-12',
		'series':'double dragon'
	},
	'doug':{
		'title': "Doug's Big Game",
		'source':'ImaginEngine',
		'sourceurl':'https://en.wikipedia.org/wiki/Backbone_Entertainment',
		'defaulttext':"Have I been stood up?",
		'platform':'gameboy',
		'year':2000,
		'gameinfo':'https://www.mobygames.com/game/gameboy-color/disneys-doug-dougs-big-game',
		'added':'2019-05-26',
	},
	'dw':{
		'title': 'DreamWeb',
		'source':'Creative Reality',
		'sourceurl':'https://en.wikipedia.org/wiki/DreamWeb',
		'defaulttext':"--                       mailbox\nCHEMOCLEAN\n\n>read sparkes\nMessage from user 23445 Jake\nSparkes.\n\nRyan, you're fired. Get in here,\ntake your stuff and get out. I\ncan't pay a loser like you to\nwaste my time. PS. If you need a\nreference, you got it.\n\n>\u2588",
		'play':'https://archive.org/details/DreamWeb_1020',
		'platform':'dos',
		'year':1994,
		'added':'2018-12-02',
		'gameinfo':'https://www.mobygames.com/game/dreamweb'
	},
	'dn1':{
		'title': 'Duke Nukem 1',
		'source':'Apogee Software',
		'sourceurl':'https://en.wikipedia.org/wiki/3D_Realms',
		'defaulttext':"You're wrong, Proton\nbreath.  I'll be done\nwith you and still have\ntime to watch Oprah!",
		'play':"https://archive.org/details/DukeNukem",
		'platform':'dos',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/dos/duke-nukum-episode-1-shrapnel-city',
		'added':'2018-01-08',
		'series':'duke nukem'

	},
	'ecco1':{
		'title': 'Ecco the Dolphin',
		'source':'Novotrade International',
		'sourceurl':'https://en.wikipedia.org/wiki/Appaloosa_Interactive',
		'defaulttext':"\n\nThe marks on \nyour head look \nlike stars in \nthe sky  ",
		'platform':'genesis',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/ecco-the-dolphin',
		'added':'2018-04-27',
		'series':'ecco'

	},
	'edit':{
		'title': 'EDIT.COM',
		'source':'Microsoft',
		'sourceurl':'https://en.wikipedia.org/wiki/Microsoft',
		'defaulttext':"",
		'platform':'dos',
		'year':1991,
		'gameinfo':'https://en.wikipedia.org/wiki/MS-DOS_Editor',
		'added':'2018-04-15',
	},
	'ed':{
		'title': 'Emerald Dragon',
		'source':'Alfa System',
		'sourceurl':'https://en.wikipedia.org/wiki/Alfa_System',
		'defaulttext':"Don't be afraid. We\ndragons are very\ngentle.",
		'platform':'snes',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/emerald-dragon_',
		'added':'2020-07-04',
	},
	'exodus':{
		'title': 'Exodus',
		'source':'Wisdom Tree',
		'sourceurl':'https://en.wikipedia.org/wiki/Wisdom_Tree',
		'defaulttext':"\nPlayer  1\nLevel   1\n\nPress SPACE to start level...",
		'platform':'dos',
		'year':1991,
		'gameinfo':'https://en.wikipedia.org/wiki/Wisdom_Tree',
		'added':'2020-02-23',
	},
	'familyfeud':{
		'title': 'Family Feud',
		'source':'Imagineering',
		'sourceurl':'https://en.wikipedia.org/wiki/Imagineering_(company)',
		'defaulttext':"  Name something\n that some people\n are embarrassed\n  to admit that\n    they wear\nToupee",
		'platform':'snes',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/snes/family-feud_',
		'added':'2020-09-25',
	},
	'fatalfuryspecial':{
		'title': 'Fatal Fury Special',
		'source':'SNK',
		'sourceurl':'https://en.wikipedia.org/wiki/SNK',
		'defaulttext':"Oh, Andy. You've become so\nstrong. Not!",
		'platform':'arcade',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/fatal-fury-2',
		'added':'2020-03-21',
		'updated':'2020-03-22'
	},
	'faxanadu':{
		'title': 'Faxanadu',
		'source':'Nihon Falcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Nihon_Falcom',
		'defaulttext':"This is not \nenough Golds.",
		'platform':'nes',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/faxanadu',
		'added':'2020-03-30',
	},
	'fwbt':{
		'title': 'The Frog for Whom the Bell Tolls',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"Hey, old man!\nWhat is it?",
		'year':1992,
		'platform':'gameboy',
		'added':'2019-02-13',
		'gameinfo':'https://www.mobygames.com/game/kaeru-no-tame-ni-kane-wa-naru',
	},
	'ff6':{
		'title': 'Final Fantasy VI',
		'source':'Square',
		'sourceurl':'https://en.wikipedia.org/wiki/Square_Enix',
		'defaulttext':"KEFKA: Hee, hee!\nNothing can beat the music of\nhundreds of voices screaming\nin unison!",
		'year':1994,
		'platform':'snes',
		'series':'final fantasy',
		'added':'2018-12-28',
		'gameinfo':'https://www.mobygames.com/game/final-fantasy-iii__',
	},
	'ff7':{
		'title': 'Final Fantasy VII',
		'source':'Square',
		'sourceurl':'https://en.wikipedia.org/wiki/Square_Enix',
		'defaulttext':"Aeris\n\u201CCloud, why don't you\n    dress up like a girl?\n    It's the only way.\u201D",
		'platform':'ps1',
		'year':1997,
		'series':'final fantasy',
		'added':'2018-04-27',
		'updated':'2020-04-09',
		'gameinfo':'https://www.mobygames.com/game/final-fantasy-vii'
	},
	'fft':{
		'title': 'Final Fantasy Tactics',
		'source':'Square',
		'sourceurl':'https://en.wikipedia.org/wiki/Square_Enix',
		'defaulttext':"[red]Lede[/]\nWe'll burn you to death,\nso don't run away.",
		'platform':'ps1',
		'year':1997,
		'series':'final fantasy',
		'added':'2020-06-14',
		'gameinfo':'https://www.mobygames.com/game/playstation/final-fantasy-tactics'
	},
	'finalfight1':{
		'title': 'Final Fight 1',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"At the center of the problem is the\nhuge gang known as Mad Gear. Mad Gear\ncontrols all of the major criminal\nactivity in the city.",
		"year":1989,
		"platform":"arcade",
		"series":"final fight",
		'gameinfo':'https://www.mobygames.com/game/arcade/final-fight',
		'added':'2018-10-31',

	},
	'fbib':{
		'title': 'Flintstones: Burgertime in Bedrock',
		'source':'Conspiracy',
		'sourceurl':'https://en.wikipedia.org/wiki/Conspiracy_Entertainment',
		'defaulttext':"Yabba Dabba Doo!",
		"year":2000,
		"platform":"gameboy",
		'gameinfo':'https://www.mobygames.com/game/gameboy-color/flintstones-burgertime-in-bedrock',
		'added':'2020-01-17',
	},
	'f13':{
		'title': 'Friday the 13th',
		'source':'Atlus',
		'sourceurl':'https://en.wikipedia.org/wiki/Atlus',
		'defaulttext':"You have finally managed\nto defeat Jason ...\nBut is he really dead ? \nWe're not telling !\nEnd..",
		"year":1989,
		"platform":"nes",
		'gameinfo':'https://www.mobygames.com/game/nes/friday-the-13th',
		'added':'2019-09-13'
	},
	'garfield':{
		'title': 'Garfield: Week of Garfield',
		'source':'Towa Chiki',
		'sourceurl':'https://en.wikipedia.org/wiki/Towa_Chiki',
		'year':1989,
		'platform':'nes',
		'defaulttext':"Did you\n find Odie?",
		'added':'2019-01-15',
		'gameinfo':'https://www.mobygames.com/game/nes/garfield-no-isshkan-a-week-of-garfield'
	},
	'gijoe':{
		'title': 'GI Joe: The Atlantis Factor',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'year':1992,
		'platform':'nes',
		'defaulttext':"Find the enemy\n\non the route.",
		'added':'2019-07-12',
		'gameinfo':'https://www.mobygames.com/game/gi-joe-the-atlantis-factor-'
	},
	'gizmos':{
		'title': 'Gizmos & Gadgets!',
		'source':'The Learning Company',
		'sourceurl':'https://en.wikipedia.org/wiki/The_Learning_Company',
		'year':1993,
		'platform':'dos',
		'defaulttext':"Morty Maxwell, the Master of\nMischief, has moved into the Shady Glen\nTechnology Center and taken over as\nthe head scientist!",
		'added':'2020-04-17',
		'gameinfo':'https://www.mobygames.com/game/super-solvers-gizmos-gadgets'
	},
	'got':{
		'title': 'God of Thunder',
		'source':'Adept Software',
		'sourceurl':'https://en.wikipedia.org/wiki/God_of_Thunder_(video_game)',
		'defaulttext':"My son, I know it is fun\nto shoot people, but if\nyou kill all the good\nguys you'll never complete\nyour mission.",
		'play':"https://archive.org/details/msdos_God_of_Thunder_1993",
		'platform':'dos',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/dos/god-of-thunder',
		'added':'2018-10-14',

	},
	'gr':{
		'title': 'Gold Rush!',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'Last words: ',
		'platform':'dos',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/dos/gold-rush',
		'added':'2018-04-15',

	},
	'g13':{
		'title': 'Golgo-13',
		'source':'Vic Tokai',
		'sourceurl':'https://en.wikipedia.org/wiki/Tokai_Communications',
		'defaulttext':"You shouldn't \nbe proud of \nclearing\neveryone out in \nrapid fire.",
		'platform':'nes',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/nes/golgo-13-top-secret-episode',
		'added':'2018-04-21',

	},
	'hrr':{
		'title': 'Hamtaro: Rainbow Rescue',
		'source':'AlphaDream',
		'sourceurl':'https://en.wikipedia.org/wiki/AlphaDream',
		'defaulttext':"It's over there! Let's \ngo see it! It's right\nover there!",
		'platform':'gba',
		'year':2003,
		'added':'2020-07-14',
		'series':'hamtaro',
		'gameinfo':'https://www.mobygames.com/game/hamtaro-rainbow-rescue'
	},
	'ha2':{
		'title': 'Home Alone 2',
		'source':'Imagineering, Inc.',
		'sourceurl':'https://en.wikipedia.org/wiki/Imagineering_(company)',
		'defaulttext':"\n\nKevin Mc Callister!\nFive feet of trouble...\nBlonde hair, Blue eyes--",
		'platform':'snes',
		'year':1992,
		'added':'2020-04-14',
		'gameinfo':'https://www.mobygames.com/game/snes/home-alone-2-lost-in-new-york_'
	},
	'hso':{
		'title': 'Hypnospace Outlaw',
		'source':'Tendershoot, Michael Lasch, ThatWhichIs Media',
		'sourceurl':'http://www.hypnospace.net/team.html',
		'defaulttext':'CARL PARKER III\nwhat, the hell',
		'platform':'win32',
		'year':2019,
		'added':'2019-03-15',
		'gameinfo':'http://www.hypnospace.net/'
	},
	'it':{
		'title': 'Iron Tank',
		'source':'SNK',
		'sourceurl':'https://en.wikipedia.org/wiki/SNK',
		'defaulttext':'"SNAKE!"\n"Watch out -use radar-\ngigantic enemy objects\nup ahead!"',
		'platform':'nes',
		'year':1988,
		'added':'2018-12-30',
		'gameinfo':'https://www.mobygames.com/game/nes/iron-tank-the-invasion-of-normandy'
	},
	'jackbros':{
		'title': "Jack Bros.",
		'source':'Atlus',
		'sourceurl':'https://en.wikipedia.org/wiki/Atlus',
		'defaulttext':"This is\nAngel's floor.\n···Why is\nAngel here?",
		'platform':'virtualboy',
		'year':1995,
		'added':'2020-07-27',
		'gameinfo':'https://www.mobygames.com/game/jack-bros',
		'series':'shin megami tensei'
	},
	'jojo':{
		'title': "JoJo's Bizarre Adventure",
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"Stupid people can believe in anything,\nso you can believe in yourself!",
		'platform':'arcade',
		'year':1998,
		'added':'2020-03-18',
		'gameinfo':'https://www.mobygames.com/game/jojos-bizarre-adventure'
	},
	'karnovr':{
		'title': "Karnov's Revenge",
		'source':'Data East',
		'sourceurl':'https://en.wikipedia.org/wiki/Data_East',
		'defaulttext':"YOU ARE A LOUSY FIGHTER,\nAND YOUR FEET STINK!",
		'platform':'arcade',
		'year':1994,
		'added':'2019-11-16',
		'updated':'2019-11-17',
		'gameinfo':'https://www.mobygames.com/game/fighters-history-dynamite',
		'series':'fighters history'
	},
	'km':{
		'title': 'Kick Master',
		'source':'KID',
		'sourceurl':'https://en.wikipedia.org/wiki/KID',
		'defaulttext':"There's one of the\nscummy living skeletons\nwho attacked the King!\nLet's get him!",
		'platform':'nes',
		'year':1992,
		'added':'2019-01-06',
		'gameinfo':'https://www.mobygames.com/game/nes/kick-master'
	},
	'kc':{
		'title': 'Kickle Cubicle',
		'source':'Irem',
		'sourceurl':'https://en.wikipedia.org/wiki/Irem',
		'defaulttext':"The beautiful Fantasy Kingdom is now under the rule of the Wizard King.",
		'platform':'nes',
		'year':1990,
		'added':'2020-02-14',
		'gameinfo':'https://www.mobygames.com/game/kickle-cubicle'
	},
	'kof94':{
		'title': 'King of Fighters \'94',
		'source':'SNK',
		'sourceurl':'https://en.wikipedia.org/wiki/SNK',
		'defaulttext':"GO HOME AND\nENJOY SPORTS!",
		'platform':'arcade',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/king-of-fighters-94',
		'added':'2020-07-05',
		'series':'king of fighters'
	},
	'kok':{
		'title': 'King of Kings',
		'source':'Wisdom Tree',
		'sourceurl':'https://en.wikipedia.org/wiki/Wisdom_Tree',
		'defaulttext':"Who was the mother of\nJesus?\n(Matthew 1:18)\n\n\n\n\n  Martha\n  Mary\n  Joanna",
		'platform':'nes',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/nes/king-of-kings-the-early-years',
		'added':'2020-02-23',
	},
	'kq4':{
		'title': 'King\'s Quest 4',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'    "Thank you for playing\n           King\'s Quest IV,\n      `The Perils of Rosella.\'\n\nNext time... be more careful!"',
		'platform':'dos',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/kings-quest-iv-the-perils-of-rosella',
		'added':'2018-01-25',
		'series':'kings quest'

	},
	'kq5':{
		'title': 'King\'s Quest 5',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'"There\'s nothing interesting around here.\nCome on!"',
		'play':"https://archive.org/details/msdos_Kings_Quest_V_-_Absence_Makes_the_Heart_Go_Yonder_1990",
		'platform':'dos',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/kings-quest-v-absence-makes-the-heart-go-yonder',
		'added':'2018-03-19',
		'series':'kings quest'
	},
	'ka':{
		'title': 'Kirby\'s Adventure',
		'source':'HAL Laboratory',
		'sourceurl':'https://en.wikipedia.org/wiki/HAL_Laboratory',
		'defaulttext':'[red]      Normal[/]\nHit the Down Arrow\nwhen Kirby has an\nenemy in his mouth\nto copy the enemy\'s\nspecial ability!',
		'platform':'nes',
		'series':'kirby',
		'year':1993,
		'added':'2019-01-11',
		'gameinfo':'https://www.mobygames.com/game/kirbys-adventure'
	},
	'kkfeoe':{
		'title': 'Kabuki Klash',
		'source':'Racdym',
		'sourceurl':'https://en.wikipedia.org/wiki/Racjin',
		'defaulttext':"No one can defeat me!\nAt the end, the only one\nwho can defeat me is myself.",
		'platform':'arcade',
		'year':1995,
		'added':'2020-04-04',
		'gameinfo':'https://www.mobygames.com/game/kabuki-klash'
	},
	'lastblade2':{
		'title': 'Last Blade 2',
		'source':'SNK',
		'sourceurl':'https://en.wikipedia.org/wiki/SNK',
		'defaulttext':"I'm gonna bop you\nall the way to the stone age.",
		'platform':'arcade',
		'year':1998,
		'added':'2020-07-07',
		'gameinfo':'https://www.mobygames.com/game/last-blade-2'
	},
	'zelda':{
		'title': 'Legend of Zelda',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"It's dangerous to go\n alone! Take this.",
		'series': 'zelda',
		'platform':'nes',
		'year':1986,
		'gameinfo':'https://www.mobygames.com/game/legend-of-zelda',
		'added':'2018-05-21'
	},
	'lttp':{
		'title': 'Legend of Zelda: A Link To The Past',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"Link, you can do it!\nSave the Princess\u2026\nZelda is your\u2026 \u2026 \u2026",
		'series': 'zelda',
		'platform':'snes',
		'year':1991,
		'added':'2018-12-17',
		'gameinfo':'https://www.mobygames.com/game/legend-of-zelda-a-link-to-the-past'
	},
	'la':{
		'title': 'Legend of Zelda: Link\'s Awakening',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"YAHOO!   I'm\nfine, and you?!",
		'series': 'zelda',
		'platform':'gameboy',
		'year':1993,
		'added':'2019-02-13',
		'gameinfo':'https://www.mobygames.com/game/legend-of-zelda-links-awakening'	
	},
	'lsl1':{
		'title': 'Leisure Suit Larry',
		'source':'Sierra On-Line',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"I find computer games with\nadult content\n\n  a. offensive.\n  b. acceptable.\n  c. repulsive.\n  d. under my bed.",
		'series': 'leisure suit larry',
		'play':"https://archive.org/details/msdos_Leisure_Suit_Larry_1_-_Land_of_the_Lounge_Lizards_1987",
		'platform':'dos',
		'year':1987,
		'added':'2020-03-15',
		'gameinfo':'https://www.mobygames.com/game/leisure-suit-larry-in-the-land-of-the-lounge-lizards'	
	},
	'lad':{
		'title': 'Life & Death',
		'source':'The Software Toolworks',
		'sourceurl':'https://en.wikipedia.org/wiki/The_Software_Toolworks',
		'defaulttext':"Your patient has died of a burst\nappendix.  Report immediately to medical\nschool and pay attention!",
		'play':"https://archive.org/details/msdos_Life_and_Death_1988",
		'platform':'dos',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/life-death',
		'added':'2018-04-19',

	},
	'llac':{
		'title': "Let's Learn About Computers",
		'source':'Troll Associates',
		'sourceurl':'https://archive.org/search.php?query=subject%3A%22trollassociates%22',
		'defaulttext':"floppy disk\nA disk is like a\nlittle record.\nYou can save\ndata on a disk\nand then use it\nlater to tell\nyour computer\nwhat to do.",
		'platform':'apple2',
		'year':1994,
		'gameinfo':'https://ia800903.us.archive.org/6/items/LetsLearnAboutComputers4amCrack/Let%27s%20Learn%20About%20Computers%20%284am%20crack%29.txt',
		'added':'2020-09-19',
		'play':'https://archive.org/details/LetsLearnAboutComputers4amCrack'
	},
	'ln':{
		'title': 'Little Nemo',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"     Nemo: I bet she's still\n           a girl.",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/little-nemo-the-dream-master',
		'added':'2019-07-26'
	},
	'lockon':{
		'title': 'Lock On',
		'source':'Copya Systems',
		'sourceurl':'https://www.mobygames.com/company/shangri-la',
		'defaulttext':"The MIG-37 is a mach 3\naircraft utilizing the\nlatest stealth\ntechnology!",
		'platform':'snes',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/lock-on_',
		'added':'2020-05-11'
	},
	'madden95':{
		'title': "Madden NFL '95",
		'source':'EA Sports',
		'sourceurl':'https://en.wikipedia.org/wiki/EA_Sports',
		'defaulttext':"Although the two-time defending Super Bowl champs have a new coach this year, the core of their team returns.",
		'platform':'genesis',
		'year':1994,
		'added':'2019-10-01',
		'gameinfo':'https://www.mobygames.com/game/madden-nfl-95',
		'series':'madden'
	},
	'ms':{
		'title': 'Major Stryker',
		'source':'Apogee Software',
		'sourceurl':'https://en.wikipedia.org/wiki/3D_Realms',
		'defaulttext':"Major Stryker, this is Fleet\nAdmiral Yoshira.  Due to the\ncritical importance of your mission\nI'll personally monitor your\nsuccess and feed you new data as\nintelligence gathers it.",
		'play':"https://archive.org/details/msdos_Major_Stryker_1993",
		'platform':'dos',
		'year':1993,
		'added':'2019-01-08',
		'contributions':[{
			'type':'high-res redraw',
			'contributor': '@HDoomguy',
			'url' :'https://twitter.com/HDoomguy',
		}],
		'gameinfo':'https://www.mobygames.com/game/major-stryker'
	},
	'mh1':{
		'title': 'Manhunter: New York',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"Now, let's back up to a few\nminutes before you made\nyour fatal mistake...",
		'platform':'dos',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/manhunter-new-york',
		'added':'2018-01-05',
		'series':'manhunter'
	},
	'mpa':{
		'title': 'Mario Party Advance',
		'source':'Hudson Soft',
		'sourceurl':'https://en.wikipedia.org/wiki/Hudson_Soft',
		'defaulttext':'Mushroom Challenge time! Spin the wheel!',
		"year":2005,
		'gameinfo':'https://www.mobygames.com/game/mario-party-advance',
		"platform":"gba",
		'series':'mario party',
		'added':'2020-04-09'
	},
	'msh':{
		'title': 'Marvel Super Heroes',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"I hear they're looking for people at the\nclown college.",
		'platform':'arcade',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/marvel-super-heroes',
		'added':'2020-03-17'
	},
	'moo':{
		'title': 'Master of Orion',
		'source':'Simtex',
		'sourceurl':'https://en.wikipedia.org/wiki/Simtex',
		'defaulttext':'Make your childish threats. The young of the Meklar often throw tantrums as well.',
		'platform':'dos',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/master-of-orion',
		'added':'2019-04-23',
		'series':'master of orion'
	},
	'mbtt':{
		'title': 'Mavis Beacon Teaches Typing',
		'source':'The Software Toolworks',
		'sourceurl':'https://en.wikipedia.org/wiki/The_Software_Toolworks',
		'defaulttext':"[cyan]Mrs. Grimley (to her dog):  \"Oh[/]\n[blue]Mrs. Grimley[/][white]:_My dog's_[/][blue]g[/]ot no__\n\n[cyan]dear, what kind of cheese\n[white]nose![/] [cyan]_\n\nshould I put on our pizza?\"\n\nDog: \"Mutts-arella!\"",
		'play':"https://archive.org/details/msdos_Mavis_Beacon_Teaches_Typing_1987",
		'platform':'dos',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/mavis-beacon-teaches-typing',
		'added':'2018-05-31',

	},
	'mm2':{
		'title': 'Mega Man 2',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"\n-W-\n\n GET EQUIPPED\n\n WITH\n\n LEAF SHIELD",
		'gameinfo':'https://www.mobygames.com/game/nes/mega-man-2',
		'platform':'nes',
		'series':'megaman',
		'added':'2019-06-03',
		'year':1989
	},
	'mmbn1':{
		'title': 'Mega Man Battle Network 1',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"Lan!! Jack into the\noven! Use the\nR Button!",
		'gameinfo':'https://www.mobygames.com/game/mega-man-battle-network',
		'platform':'gba',
		'series':'megaman',
		'added':'2018-10-19',
		'year':2001
	},
	'mmx1':{
		'title': 'Mega Man X 1',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"You worthless piece\nof scrap metal, did\nyou think you\ncould defeat me?",
		'gameinfo':'https://www.mobygames.com/game/snes/mega-man-x',
		'platform':'snes',
		'series':'megaman',
		'added':'2018-10-27',
		'year':1993
	},
	'mgs':{
		'title': 'Metal Gear Solid',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"I can't believe I'm being hit on\nby the famous Solid Snake...",
		'gameinfo':'https://www.mobygames.com/game/metal-gear-solid',
		'platform':'ps1',
		'series':'metal gear',
		'added':'2018-03-07',
		'year':1999
	},
	'metroid':{
		'title': 'Metroid',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':'           GREAT!\n YOU FULFILED YOUR MISSION.\n IT WILL REVIVE PEACE IN\nSPACE. \n BUT,IT MAY BE INVADED BY\nTHE OTHER METROID.\n PRAY FOR A TRUE PEACE IN\nSPACE',
		'platform':'nes',
		'year':1986,
		'gameinfo':'https://www.mobygames.com/game/metroid',
		'added':'2018-04-10',
		'series':'metroid',
	},
	'mmprtm':{
		'title': 'Mighty Morphin Power Rangers: The Movie',
		'source':'Sims',
		'sourceurl':'https://en.wikipedia.org/wiki/SIMS_Co.,_Ltd.',
		'defaulttext':'Please remember the difference\nbetween fantasy and reality.\nDo your fighting on the screen,\nnot at home or at school.',
		'platform':'genesis',
		'series':'power rangers',
		'year':1995,
		'added':'2018-11-06',
		'gameinfo':'https://www.mobygames.com/game/genesis/mighty-morphin-power-rangers-the-movie__'
	},
	'milon':{
		'title': "Milon's Secret Castle",
		'source':'Hudson Soft',
		'sourceurl':'https://en.wikipedia.org/wiki/Hudson_Soft',
		'defaulttext':'MAY I HELP YOU\n\n?',
		'platform':'nes',
		'year':1986,
		'added':'2021-02-22',
		'gameinfo':'https://www.mobygames.com/game/milons-secret-castle'
	},
	'minishcap':{
		'title': 'Legend of Zelda: The Minish Cap',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"If only we had some way to defend\nourselves against [blue]those nuts of his[/].",
		'platform':'gba',
		'series': 'zelda',
		'year':2004,
		'gameinfo':'https://www.mobygames.com/game/gameboy-advance/legend-of-zelda-the-minish-cap',
		'added':'2019-10-25',
	},
	'minit':{
		'title': 'Minit',
		'source':'Jan Willem Nijman, Kitty Calis, Jukio Kallio, and Dominik Johann',
		'sourceurl':'https://en.wikipedia.org/wiki/Minit_(video_game)',
		'defaulttext':'Hello there...',
		'platform':'win32',
		'year':2018,
		'gameinfo':'https://www.mobygames.com/game/minit',
		'added':'2018-04-25',

	},
	'mfpl':{
		'title': 'Minnesota Fats: Pool Legend',
		'source':'Data East',
		'sourceurl':'https://en.wikipedia.org/wiki/Data_East',
		'defaulttext':'So, you think you can\nchallenge me? Ha Ha Ha!!',
		'platform':'genesis',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/minnesota-fats-pool-legend',
		'added':'2019-02-15',
	},
	'mi1':{
		'title': 'The Secret of Monkey Island',
		'source':'Lucasfilm Games',
		'sourceurl':'https://en.wikipedia.org/wiki/Lucasfilm_Games',
		'defaulttext':'Never pay more than 20 bucks\nfor a computer game.',
		'platform':'dos',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/secret-of-monkey-island',
		'added':'2019-12-12',
		'series':'monkey island'
	},
	'mk2':{
		'title': 'Mortal Kombat II',
		'source':'Midway',
		'sourceurl':'https://en.wikipedia.org/wiki/Mortal_Kombat_II',
		'defaulttext':'Can you take the cold?',
		'contributions':[{
			'contributor': '@pixel_data',
			'url':'https://twitter.com/pixel_data',
		}],
		'platform':'arcade',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/mortal-kombat-ii',
		'added':'2018-04-02',
		'series':'mortal kombat'
	},
	'mt32':{
		'title': 'MT-32',
		'source':'Roland',
		'sourceurl':'https://en.wikipedia.org/wiki/Roland_MT-32',
		'defaulttext':' ** Roland MT-32 ** ',
		'contributions':[{
			'contributor': '@NoxicoDev',
			'url':'https://twitter.com/noxicodev',
		}],
		'platform':'hardware',
		'year':1987,
		'gameinfo':'https://en.wikipedia.org/wiki/Roland_MT-32',
		'added':'2018-04-11',

	},
	'nesticle':{
		'title': 'Nesticle',
		'source':'Bloodlust Software',
		'sourceurl':'https://en.wikipedia.org/wiki/NESticle',
		'defaulttext':'Bow to the fecal-lord\n\nNESticle DOS                 [red]V0.34[/]\nWatcom C++ 10.60 Jun 13 1997 16:12:18\n\nCopyright (C) 1997 Bloodlust Software\n\nThanks Shitman!',
		'platform':'dos',
		'year':1997,
		'gameinfo':'https://web.archive.org/web/20161116081727/bloodlust.zophar.net/NESticle/nes.html',
		'added':'2019-11-18',
	},
	'neutopia':{
		'title': 'Neutopia',
		'source':'Hudson Soft',
		'sourceurl':'https://en.wikipedia.org/wiki/Hudson_Soft',
		'defaulttext':'The demon boss in this sphere is ugly indeed and he is also very powerful.              \uD83E\uDC47',
		'platform':'turbografx16',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/neutopia',
		'added':'2020-06-30',
	},
	'ng':{
		'title': 'Ninja Gaiden',
		'source':'Tecmo',
		'sourceurl':'https://en.wikipedia.org/wiki/Tecmo',
		'defaulttext':'"Just a girl.\n Get out of here!"',
		'platform':'nes',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/nes/ninja-gaiden',
		'added':'2018-04-20',
		'series':'ninja gaiden',

	},
	'odallus':{
		'title': 'Odallus',
		'source':'JoyMasher',
		'sourceurl':'https://joymasher.com/',
		'defaulttext':"GODS? OUR GODS ARE\nDEAD, OLD AND NEW,\nI'M MY OWN GOD NOW!",
		'year':2015,
		'platform':'win32',
		'added':'2019-01-31',
		'gameinfo':'https://www.mobygames.com/game/odallus-the-dark-call'
	},
	'oregon':{
		'title': 'Oregon Trail',
		'source':'MECC',
		'sourceurl':'https://en.wikipedia.org/wiki/MECC',
		'defaulttext':"     Here lies\n       andy\n\npeperony and\nchease",
		'play':"https://archive.org/details/msdos_Oregon_Trail_The_1990",
		'platform':'apple2',
		'year':1985,
		'gameinfo':'https://www.mobygames.com/game/oregon-trail',
		'added':'2018-04-04',

	},
	'pma':{
		'title': "Pac-Man Arrangement",
		'source':'Namco',
		'sourceurl':'https://en.wikipedia.org/wiki/Namco',
		'defaulttext':" [yellow]TAKE A BOW![/]\n\n[blue]You've finished the game.[/]\n[pink]\nBut \nTHE GAME NEVER REALLY ENDS.[/]\n[green]\nSOMEONE,\nSOMEWHERE \nIS BEING CHASED BY MONSTERS!",
		'platform':'arcade',
		'year':1996,
		'gameinfo':'https://www.mobygames.com/game/namco-classic-collection-vol',
		'series':'pac-man',
		'added':'2020-09-29'
	},
	'phdq':{
		'title': "Paris Hilton's Diamond Quest",
		'source':'Gameloft',
		'sourceurl':'https://en.wikipedia.org/wiki/Gameloft',
		'defaulttext':"You're a total\nEinstein, Baby.\nSmarts are hot.",
		'platform':'j2me',
		'year':2006,
		'gameinfo':'https://www.mobygames.com/game/paris-hiltons-diamond-quest',
		'added':'2020-05-09',
	},
	'pictionary':{
		'title': 'Pictionary',
		'source':'Software Creations',
		'sourceurl':'https://en.wikipedia.org/wiki/Acclaim_Studios_Manchester',
		'defaulttext':"   Congratulations to\n      Potato Brains\n\n   You're the best!!!",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/pictionary-the-game-of-video-quick-draw',
		'added':'2020-08-26'
	},
	'pokemon':{
		'title': 'Pokemon',
		'source':'Game Freak',
		'sourceurl':'https://en.wikipedia.org/wiki/Game_Freak',
		'defaulttext':'         CHARMANDER\nGary: WHAT?\nUnbelievable!',
		'platform':'gameboy',
		'year':1998,
		'gameinfo':'https://www.mobygames.com/game/pokmon-red-version',
		'added':'2018-04-04',
		'series':'pokemon'
	},
	'pokesnap':{
		'title': 'Pokemon Snap',
		'source':'HAL Laboratory',
		'sourceurl':'https://en.wikipedia.org/wiki/HAL_Laboratory',
		'defaulttext':'Here on Pok\u00E9mon Island,\nwild Pok\u00E9mon can be\nfound everywhere.',
		'platform':'n64',
		'year':1999,
		'gameinfo':'https://www.mobygames.com/game/pokmon-snap',
		'added':'2020-01-26',
		'series':'pokemon'
	},
	'pq2':{
		'title': 'Police Quest 2',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'Thank you for playing Police\nQuest 2. Next time, be a little more\ncareful.',
		'platform':'dos',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/police-quest-2-the-vengeance',
		'added':'2017-10-26',
		'series':'police quest'
	},
	'pq3':{
		'title': 'Police Quest 3',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"Those curbs just sneak right\n    up on you, don't they?",
		'platform':'dos',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/police-quest-3-the-kindred',
		'added':'2018-12-18',
		'series':'police quest'
	},
	'pw':{
		'title': 'Pilotwings',
		'source':'Nintendo',
		'sourceurl':"https://en.wikipedia.org/wiki/Nintendo",
		'defaulttext':"        Lesson 1\nHi, I am Tony,  and I'll\nbe  your  instructor for \nArea 1.     Our  lessons\nwill cover a few basics-\nlanding   an   airplane,\nand skydiving\nfor accuracy.",
		'gameinfo':'https://www.mobygames.com/game/snes/pilotwings',
		'year':1991,
		'added':'2019-02-16',
		'platform':'snes'

	},
	'wea':{
		'title': 'Presidental Alert',
		'source':'FEMA',
		'sourceurl':"https://www.fema.gov/emergency-alert-test",
		'defaulttext':"THIS IS A TEST of the National\nWireless Emergency Alert System.\nNo action is needed.",
		'platform':'android',
		'year':2018,
		'gameinfo':'https://en.wikipedia.org/wiki/Wireless_Emergency_Alerts',
		'added':'2018-10-04',

	},
	'psh':{
		'title': 'Pugsley\'s Scavenger Hunt',
		'source':'Ocean',
		'sourceurl':"https://en.wikipedia.org/wiki/The_Addams_Family_(video_game_series)#The_Addams_Family:_Pugsley's_Scavenger_Hunt",
		'defaulttext':"This door is\n locked.\nwhy not come back \n later ?",
		'platform':'nes',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/addams-family-pugsleys-scavenger-hunt',
		'added':'2018-06-15',

	},
	"raid2020":{
		'title': 'Raid 2020',
		'source':'Color Dreams',
		'sourceurl':'https://en.wikipedia.org/wiki/Wisdom_Tree',
		'defaulttext':"A.D.2020. A plague of\n\nnarcotics transcending\n\nthe bounds of race, \n\neconomy, and time have\n\nput a strangle hold on\n\namerica. You must destroy\n\npitbull, the drug kingpin\n\nwho has become the overlord \n\nof this sinister empire.\n\n\nYou, Shadow, are\n\nthe last hope ... ",
		'platform':'nes',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/raid-2020',
		'added':'2020-04-21',
	},
	"rt":{
		'title': 'Railroad Tycoon',
		'source':'MPS Labs',
		'sourceurl':'https://en.wikipedia.org/wiki/MicroProse',
		'defaulttext':"Labor Violence!\nMilitia Called Out!\nRecession Feared.",
		'play':"https://archive.org/details/railroad_tycoon_1990",
		'platform':'dos',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/sid-meiers-railroad-tycoon',
		'added':'2018-06-02',
		'series':'railroad tycoon'
	},
	"rambo":{
		'title': 'Rambo',
		'source':'Pack-in-Video',
		'sourceurl':'https://en.wikipedia.org/wiki/Pack-In-Video',
		'defaulttext':"Your mission is to\nsneak into the\nenemy camp and find\nthem.\nAre you up to it?\nI'm not afraid of\ndeath.\n\nI feel better in\nprison.",
		'platform':'nes',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/rambo_',
		'added':'2020-09-26',
		'series':'rambo'
	},
	"rr":{
		'title': 'Road Rash',
		'source':'Electronic Arts',
		'sourceurl':'https://en.wikipedia.org/wiki/Electronic_Arts',
		'defaulttext':"It's a great day to\nface challenge on \nthe open road. Best\nof luck friend!",
		'platform':'genesis',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/road-rash',
		'added':'2018-04-15',
		'series':'road rash'
	},
	"robocop":{
		'title': 'RoboCop',
		'source':'Ocean',
		'sourceurl':'https://en.wikipedia.org/wiki/Ocean_Software',
		'defaulttext':"\n\nPrime directives\n\n1. Serve the public \n   trust\n\n2. Protect the \n   innocent\n\n3. Uphold the law",
		'platform':'gameboy',
		'year':1988,
		'gameinfo':'https://www.mobygames.com/game/robocop__',
		'added':'2020-06-17'
	},
	"rygar":{
		'title': 'Rygar',
		'source':'Tecmo',
		'sourceurl':'https://en.wikipedia.org/wiki/Tecmo',
		'defaulttext':"from this\npoint you\ncan't go on\nwithout\ncrossbow.",
		'platform':'nes',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/nes/rygar',
		'added':'2018-05-09',
	},
	'scnes':{
		'title': 'SimCity NES',
		'source':'Maxis Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Maxis',
		'defaulttext':"[bigwhite]    Tokyo,Japan 1961[/]\n[black] A large reptilian crea-\nture has been spooted\nheading for Tokyo. It\nseems to be attracted to\nthe heavy levels of in-\ndustrial pollution there.\n Try to control the\nfires,then rebuild the\nindustrial center.You \nhave 5 years.",
		'platform': 'nes',
		'series':'simcity',
		'year':1991,
		'added':'2019-01-01',
		'gameinfo':'https://gamehistory.org/simcity/'
	},
	'sc2k':{
		'title': 'SimCity 2000',
		'source':'Maxis Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Maxis',
		'defaulttext':"YOU CAN'T CUT BACK ON\nFUNDING! YOU WILL\nREGRET THIS!",
		'play':"https://archive.org/details/msdos_SimCity_2000_-_CD_Collection_1994",
		'platform':'dos',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/simcity-2000',
		'added':'2017-12-18',
		'updated':'2019-02-23',
		'series':'simcity'
	},
	'simrefinery':{
		'title': 'SimRefinery',
		'source':'Maxis Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Maxis',
		'defaulttext':"Hydrocracker\nHydrocracker Unit cracks heavy oil into\nlighter components (in effect, synthetic\nmixtures), using a catalyst in the presence of\nhydrogen.",
		'platform':'dos',
		'year':1992,
		'gameinfo':'https://en.wikipedia.org/wiki/SimRefinery',
		'added':'2020-06-04',
		'added':'2020-06-20',
	},
	'sqta':{
		'title': 'Simon Quest: Transylvania Adventure',
		'source':'Programancer',
		'sourceurl':'https://twitter.com/Programancer',
		'defaulttext':"The old man in the \nhouse with no torches\ncan show you the way.",
		'gameinfo':"https://programancer.itch.io/simon-quest",
		'play':"https://programancer.itch.io/simon-quest",
		'where-to-use':'itch.io',
		'platform':'win32',
		'year':2019,
		'added':'2019-07-06',
	},
	'sr':{
		'title':'Shadowrun',
		'source':'Beam Software',
		'sourceurl':'https://en.wikipedia.org/wiki/Beam_Software',
		'platform':'snes',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/shadowrun_',
		'defaulttext':"[bold]Dog[/bold] controls your \ndestiny. Seek out three\nitems of his favor and\nthen seek his shrine.",
		'added':'2019-02-17',
	},
	'sod':{
		'title': 'Skate or Die',
		'source':'Ultra Games (Konami)',
		'sourceurl':'https://en.wikipedia.org/wiki/Ultra_Games',
		'defaulttext':"Do your\nfolks\nknow what\nyer doing",
		'year':1988,
		'platform':'nes',
		'added':'2019-01-01',
		'gameinfo':'https://www.mobygames.com/game/nes/skate-or-die'
	},
	'skitchin':{
		'title': "Skitchin'",
		'source':'Electronic Arts',
		'sourceurl':'https://en.wikipedia.org/wiki/Electronic_Arts',
		'defaulttext':"Wait until your mother hears about this. It'll break her heart! She had dreams about you being a highly paid programmer. Instead you'll be a poor dead skitcher! Sighhh...",
		'year':1994,
		'platform':'genesis',
		'gameinfo':'https://www.mobygames.com/game/genesis/skitchin',
		'added': '2018-12-10'
	},
	'skunkart':{
		'title': "Skunny Kart",
		'source':'Copysoft',
		'sourceurl':'https://www.mobygames.com/company/copysoft',
		'defaulttext':"PLAYER 1\n KART LEFT    : CTRL KEY\n KART RIGHT   : ALT KEY\n ACCELERATION : SHIFT KEY\n UTILITY      : TAB KEY\n\nPLAYER 2\n KART LEFT    : NUMPAD INS\n KART RIGHT   : NUMPAD DEL\n ACCELERATION : NUMPAD END\n UTILITY      : NUMPAD HOME\n      ESC TO ABORT GAME\n F9 TO CAPTURE A PCX SCREEN",
		'year':1993,
		'platform':'dos',
		'gameinfo':'https://www.mobygames.com/game/dos/skunny-kart',
		'added': '2020-08-01',
		'play':'https://archive.org/details/msdos_Skunny_Kart_1993'
	},
	'sb':{
		'title': 'Skyblazer',
		'source':'Ukiyotei',
		'sourceurl':'https://en.wikipedia.org/wiki/Ukiyotei',
		'defaulttext':"[cyan]Sky[/cyan]\nDo you not know who I am?\nI am known as Sky. ▼",
		'platform':'snes',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/snes/skyblazer',
		'added':'2018-05-15',

	},
	'sth1':{
		'title': 'Sonic The Hedgehog 1',
		'source':'Sega',
		'sourceurl':'https://en.wikipedia.org/wiki/SEGA',
		'defaulttext':"Green Hill",
		'platform':'genesis',
		'series':'sonic',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/genesis/sonic-the-hedgehog',
		'contributions':[{
			'type':'extra letters',
			'contributor': 'Ruari O\'Sullivan',
			'url':'https://twitter.com/randomnine',
		}],
		'added':'2018-10-31'
	},
	'sth2':{
		'title': 'Sonic The Hedgehog 2',
		'source':'Sega',
		'sourceurl':'https://en.wikipedia.org/wiki/SEGA',
		'defaulttext':"Emerald Hill",
		'platform':'genesis',
		'series':'sonic',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/genesis/sonic-the-hedgehog-2',
		'added':'2018-10-31'
	},
	'soulb':{
		'title': 'Soul Blazer',
		'source':'Quintet',
		'sourceurl':'https://en.wikipedia.org/wiki/Quintet_(company)',
		'defaulttext':"I used to live up\nin the sky just like\nyou.",
		'platform':'snes',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/snes/soul-blazer',
		'added':'2018-12-08'
	},
	'soulf':{
		'title': 'Soul Falchion',
		'source':'Vast Fame',
		'sourceurl':'https://bootleggames.fandom.com/wiki/Vast_Fame',
		'defaulttext':"YOU STILL GO HOME\nTO SUCK AT BREAST!",
		'platform':'gameboy',
		'year':2002,
		'gameinfo':'https://bootleggames.fandom.com/wiki/Soul_Falchion',
		'added':'2019-02-17'
	},
	'smurfs3':{
		'title': "Smurfs' Nightmare",
		'source':'Velez & Dubail',
		'sourceurl':'https://en.wikipedia.org/wiki/VD-dev',
		'defaulttext':"Go into their houses and rescue them.",
		'platform':'gameboy',
		'year':1997,
		'gameinfo':'https://www.mobygames.com/game/smurfs-nightmare',
		'added':'2020-02-01',
		'contributions':[{
			'contributor': 'Monster Go! Go! Go!!',
			'url':'https://bootleggames.fandom.com/wiki/Monster_Go!_Go!_Go!!',
		}],
	},
	'snakesrevenge':{
		'title': "Snake's revenge",
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"Snake, the pur-\npose of your\nmission is to\ninfiltrate the\nenemy's strong-\nhold.          _",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/snakes-revenge',
		'series':'metal gear',
		'added':'2020-05-16'
	},
	'spacecadet':{
		'title': 'Space Cadet Pinball',
		'source':'Cinematronics',
		'sourceurl':'https://en.wikipedia.org/wiki/Cinematronics,_LLC',
		'defaulttext':"Player 1\n\nAwaiting\nDeployment",
		'platform':'win32',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/full-tilt-pinball',
		'added':'2020-08-05'
	},
	'sq1vga':{
		'title': 'Space Quest 1',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"As you lie on the floor in a smoldering,\ncarbogelatinous heap, you just can't help\nbut wonder why you bothered getting up\nthis morning.",
		'platform':'dos',
		'year':1986,
		'gameinfo':'https://www.mobygames.com/game/space-quest-chapter-i-the-sarien-encounter',
		'added':'2018-05-08',
		"series":"space quest"

	},
	'sq3':{
		'title': 'Space Quest 3',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':"Thanks for playing Space Quest\n]I[. As usual, you've been a real\n                    hoot.",
		'platform':'dos',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/space-quest-iii-the-pirates-of-pestulon',
		'added':'2017-12-21',
		"series":"space quest"
	},
	'sq4':{
		'title': 'Space Quest 4',
		'source':'Sierra Online',
		'sourceurl':'https://en.wikipedia.org/wiki/Sierra_Entertainment',
		'defaulttext':'Just as you fade\nfrom the living \norganism club you\nthink, in\namazement, "So that\'s\nwhat my spleen looks\nlike!"',
		'platform':'dos',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/space-quest-iv-roger-wilco-and-the-time-rippers',
		'added':'2018-03-08',
		"series":"space quest"
	},
	'sv':{
		'title': 'Stardew Valley',
		'source':'ConcernedApe',
		'sourceurl':'https://en.wikipedia.org/wiki/Stardew_Valley',
		'defaulttext':"Your grandpa used to complain\nabout the rickety old bed. But\nI think, deep down, he actually\nloved that house.",
		'platform':'win32',
		'year':2016,
		'gameinfo':'https://www.mobygames.com/game/stardew-valley',
		'added':'2018-04-09',
	},
	'sw':{
		'title': 'Star Wars',
		'source':'Atari',
		'sourceurl':'https://en.wikipedia.org/wiki/Atari,_Inc.',
		'defaulttext':"     Flight instructions to red five\n\n1. Your  x  wing  is  equipped  with an\n   invisible deflector shield that will\n   protect you for 9 collisions.\n\n2. Deflector  strength  is  lost when a\n   fireball impacts your shield or when\n   you  strike a laser  tower or trench\n   catwalk.\n\n3. Aim your  lasers  with the cursor to\n   explode empire  tie  fighters, laser\n   tower tops and trench turrets.\n\n4. Shoot fireballs  before  they impact\n   your shield.\n\n5. The rebel force  is depending on you\n   to stop the empire by blowing up the\n   death star.",
		'platform':'dos',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/dos/star-wars',
		'added':'2020-09-20',
		'series':'star wars'
	},
	'sc2':{
		'title': 'Star Control II',
		'source':'Toys for Bob',
		'sourceurl':'https://en.wikipedia.org/wiki/Toys_for_Bob',
		'defaulttext':"Juffo-Wup fills in my fibers and I\ngrow turgid. Violent action ensues.",
		'platform':'dos',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/star-control-ii',
		'added':'2018-05-26',
		'series':'star control'
	},	
	'sf':{
		'title': 'Star Fox',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"what's wrong\nwith you today\nfox?!",
		'platform':'snes',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/snes/star-fox_',
		'added':'2018-05-02',
		'series':'star fox'
	},
	'sf64':{
		'title': 'Star Fox 64',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"It's about time you\nshowed up, Fox.\nYou're the only hope\nfor our world!",
		'platform':'n64',
		'year':1997,
		'gameinfo':'https://www.mobygames.com/game/n64/star-fox-64',
		'added':'2020-06-23',
		'series':'star fox'
	},
	'sttngafu':{
		'title': 'Star Trek: A Final Unity',
		'source':'Spectrum HoloByte',
		'sourceurl':'https://en.wikipedia.org/wiki/Spectrum_HoloByte',
		'defaulttext':"Welcome to Morassia. As it turns out, I'm \nconducting a little investigation of my\nown. I'm curious to know why the \nFederation allows so many male officers.\nDoesn't it cause morale problems?",
		'platform':'dos',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/star-trek-the-next-generation-a-final-unity',
		'added':'2019-04-09',
		'series':'star trek'
	},
	'stv':{
		'title': 'Star Trek V: The Final Frontier',
		'source':'Bandai',
		'sourceurl':'https://en.wikipedia.org/wiki/Bandai',
		'defaulttext':"KIRK,SPOCK,McCOY ARE FREED.\nTHEY COME TO LEARN SYBOK'S\nREAL MISSION,AND DICIDE TO\nTRAVEL TO THE CREATION\nPLANET.\n\n\n                           ▼",
		'platform':'nes',
		'year':1989,
		'gameinfo':'https://memory-alpha.fandom.com/wiki/Star_Trek_V:_The_Final_Frontier_(NES)',
		'added':'2020-05-29',
		'series':'star trek'
	},
	'stonekeep':{
		'title': 'Stonekeep',
		'source':'Interplay Productions',
		'sourceurl':'https://en.wikipedia.org/wiki/Interplay_Entertainment',
		'defaulttext':"Send a guard troop to Fort Thunder.\nThe Throgs are getting restless again.\n-Korzen",
		'platform':'dos',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/stonekeep',
		'added':'2019-02-22',
	},
	'sf2':{
		'title': 'Street Fighter 2',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Super_Street_Fighter_II',
		'defaulttext':"I'M THE STRONGEST WOMAN\nIN THE WORLD.",
		'contributions':[{
			'contributor': '@pixel_data',
			'url':'https://twitter.com/pixel_data',
		}],
		'platform':'arcade',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/street-fighter-ii-the-world-warrior',
		'added':'2018-04-03',
		'updated':'2019-02-26',
		'series':'street fighter'
	},
	'strider':{
		'title': 'Strider',
		'source':'Capcom',
		'sourceurl':'https://en.wikipedia.org/wiki/Capcom',
		'defaulttext':"It penetrates into\nyour mind and makes\nyou crazy.",
		'platform':'nes',
		'year':1989,
		'gameinfo':'https://www.mobygames.com/game/nes/strider_',
		'added':'2019-07-12'
	},
	'smas':{
		'title': 'Super Mario All-Stars',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':'Warning: It is a serious\ncrime to copy video games.\n\n18 USC 2319 Please refer\nto your Nintendo game\ninstruction booklet for\nfurther information.',
		"year":1993,
		'gameinfo':'https://www.mobygames.com/game/snes/super-mario-all-stars',
		"platform":"snes",
		'series':'mario',
		'added':'2018-10-29'
	},
	'smb':{
		'title': 'Super Mario Bros',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':'   THANK YOU MARIO!\n\nBUT OUR PRINCESS IS IN\nANOTHER CASTLE!',
		'contributions':[{
			'contributor': '@pixel_data',
			'url':'https://twitter.com/pixel_data',
		}],
		'series':'mario',
		'platform':'nes',
		'year':1985,
		'gameinfo':'https://www.mobygames.com/game/nes/super-mario-bros',
		'added':'2018-04-04',
	},
	'smrpg':{
		'title': 'Super Mario RPG',
		'source':'Square',
		'sourceurl':'https://en.wikipedia.org/wiki/Square_(company)',
		'defaulttext':" Lots of people use something\n called a \u201Cdoor\u201D to go in and out\n of their houses...",
		'platform':'snes',
		'year':1996,
		"added":"2018-12-07",
		'gameinfo':'https://www.mobygames.com/game/super-mario-rpg-legend-of-the-seven-stars'
	},
	'm64':{
		'title': 'Super Mario 64',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"Dear Mario:\nPlease come to the\ncastle. I've baked\na cake for you.\nYours truly--\nPrincess Toadstool",
		'series':'mario',
		'platform':'n64',
		'year':1996,
		'gameinfo':'https://www.mobygames.com/game/super-mario-64',
		'added':'2018-04-08',
	},
	'mario64ds':{
		'title': 'Super Mario 64 DS',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"Dear Mario:\nPlease come to the\ncastle. I've baked\na cake for you.\nYours truly--\nPrincess Toadstool",
		'series':'mario',
		'platform':'ds',
		'year':2004,
		'gameinfo':'https://www.mobygames.com/game/nintendo-ds/super-mario-64-ds',
		'added':'2021-03-02',
	},
	'smw':{
		'title': 'Super Mario World',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"Welcome!   This is\nDinosaur Land.  In\nthis strange  land\nwe    find    that\nPrincess Toadstool\nis  missing again!\nLooks  like Bowser\nis at it again!",
		'platform':'snes',
		'series':'mario',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/super-mario-world',
		'added':'2018-04-28',
		'updated':'2019-03-10'
	},
	'sm':{
		'title': 'Super Metroid',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"I first battled the Metroids\non planet Zebes. It was there\nthat I foiled the plans of\nthe Space Pirate leader\nMother Brain to use the\ncreatures to attack\ngalactic civilization...\n_",
		'platform':'snes',
		'series':'metroid',
		'year': 1994,
		'gameinfo':'https://www.mobygames.com/game/snes/super-metroid',
		'added':'2018-04-17'
	},
	'sor':{
		'title': 'Super Off Road: The Baja',
		'source':'Leland Interactive Media',
		'sourceurl':'https://en.wikipedia.org/wiki/Leland_Interactive_Media',
		'defaulttext':"[yellow]LEG 1:  San Felipe[/]\n\nKeep all wheels on\nthe road to go fast.\nAvoid hitting\nthings which\nwill damage\nyour truck.",
		'platform':'snes',
		'series':'super off road',
		'year': 1993,
		'gameinfo':'https://www.mobygames.com/game/super-off-road-the-baja',
		'added':'2020-07-01'
	},
	'superman':{
		'title': 'Superman',
		'source':'Kemco',
		'sourceurl':'https://en.wikipedia.org/wiki/Kemco',
		'platform':'nes',
		'year': 1988,
		'gameinfo':'https://www.mobygames.com/game/nes/superman_',
		'defaulttext':'\nYou are \n\nClark Kent',
		'added':'2019-02-07'
	},
	'sn':{
		'title': 'Surf Ninjas',
		'source':'NuFX',
		'sourceurl':'https://en.wikipedia.org/wiki/NuFX',
		'platform':'gamegear',
		'year': 1993,
		'gameinfo':'https://www.mobygames.com/game/surf-ninjas',
		'defaulttext':'I can offer\nno help here',
		'added':'2020-04-13'
	},
	'swatkats':{
		'title': 'SWAT Kats',
		'source':'AIM',
		'sourceurl':'https://en.wikipedia.org/wiki/Fortyfive',
		'defaulttext':" To:The Swat Kats\n FR:Mayor Manx\n\n Trouble at MadKat\n Amusement Park. Children\n disappearing. Find Them!",
		'platform':'snes',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/swat-kats-the-radical-squadron',
		'added':'2020-03-08',
	},
	'ss2':{
		'title': 'System Shock 2',
		'source':'Irrational Games and Looking Glass Studios',
		'sourceurl':'https://en.wikipedia.org/wiki/System_Shock_2',
		'defaulttext':"POLITO 12.JUL.14\nre: Dawdling\n[sep] [/]\nWhy do you go so slowly?!  Do you think this is some kind of game?  It is only through luck and my continued forbearance that you are even alive!  Now move!",
		'platform':'win32',
		'year':1999,
		'gameinfo':'https://www.mobygames.com/game/system-shock-2',
		'added':'2018-06-16',
		'series':'system shock'
	},
	'themehospital':{
		'title': 'Theme Hospital',
		'source':'Bullfrog Productions',
		'sourceurl':'https://en.wikipedia.org/wiki/Bullfrog_Productions',
		'defaulttext':"You have just killed your \nfirst patient.\nHow does it feel?",
		'platform':'dos',
		'year':1997,
		'gameinfo':'https://www.mobygames.com/game/theme-hospital',
		'added':'2020-08-08'
	},
	'tmnta':{
		'title': 'TMNT Arcade',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"Name    Leonardo\nAge     16\nHeight  5'01''\nweight  155 lbs\nweapon  katana blade\n\n\n\n Leader of the boys.\n if gets serious, his swords start\nSlicing everything in sight .....\nincluding salami pizza!",
		'platform':'arcade',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/arcade/teenage-mutant-ninja-turtles__',
		'added':'2020-03-19',
		'series':'tmnt'
	},
	'tmnt1':{
		'title': 'TMNT',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"Find and help\nyour friend\nin this stage.\n    You can\n    do it.",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/nes/teenage-mutant-ninja-turtles__',
		'added':'2018-04-23',
		'series':'tmnt',
	},
	'tjae2':{
		'title': 'ToeJam & Earl 2',
		'source':'Johnson Voorsanger Productions',
		'sourceurl':'https://en.wikipedia.org/wiki/ToeJam_%26_Earl_Productions',
		'defaulttext':"        Game Tip\nHold up on direction pad\nto shake trees, part\nbushes or push buttons.",
		'platform':'genesis',
		'year':1993,
		'gameinfo':'https://www.mobygames.com/game/toejam-earl-in-panic-on-funkotron',
		'added':'2018-04-28',
		'series':'toejam and earl'
	},
	'tr':{
		'title': 'Totally Rad',
		'source':'Aicom',
		'sourceurl':'https://en.wikipedia.org/wiki/Aicom',
		'defaulttext':"THEY ARE INTELLIGENT,\nBUT INCREDIBLY UGLY.",
		'platform':'nes',
		'year':'1991',
		'added':'2019-02-01',
		'gameinfo':'https://www.mobygames.com/game/nes/totally-rad'
	},
	'ts':{
		'title': 'Toy Story',
		'source':'Traveller\'s Tales',
		'sourceurl':'https://en.wikipedia.org/wiki/Traveller%27s_Tales',
		'defaulttext':"     That old army game\n\nopen the bucket of\nsoldiers and then\nlocate the baby \nmonitor and pass it\ndown to the sergeant's\ntroops.  The toys will\nthen meet you at the\nother baby monitor.\ngood luck and watch out\nfor the trains and\nplanes!!",
		'gameinfo':'https://www.mobygames.com/game/snes/disneys-toy-story',
		'platform':'snes',
		'year':1995,
		'added':'2018-10-25'
	},
	'ufouria':{
		'title': 'Ufouria',
		'source': 'Sunsoft',
		'sourceurl': 'https://en.wikipedia.org/wiki/Sunsoft',
		'defaulttext': 'I must fight you and\nwin so that you will\nremember that we are\nfriends.',
		'platform': 'nes',
		'year': 1991,
		'added': '2019-09-03',
		'gameinfo':'https://www.mobygames.com/game/ufouria-the-saga'
	},
	'ul': {
		'title': 'Undertale Logo',
		'source': 'Toby Fox',
		'sourceurl': 'https://en.wikipedia.org/wiki/Toby_Fox',
		'defaulttext': 'undeRtale',
		'contributions':[{
			'contributor': 'Haley Wakamatsu',
			'url':'https://www.behance.net/gallery/31378523/Monster-Friend-Undertale-Logo-Font',
		}],
		'platform': 'win32',
		'year': 2015,
		'added': '2018-11-07',
		'gameinfo':'https://www.mobygames.com/game/undertale'
	},
	'unreal':{
		'title': 'Unreal',
		'source': 'Epic MegaGames',
		'sourceurl': 'https://en.wikipedia.org/wiki/Epic_Games',
		'defaulttext': "Benjamin Nathaniel's Diary,\nday 93: Today is my birthday.\nI will celebrate by attempting\nto start another prison riot.",
		'platform': 'win32',
		'year': 1998,
		'added': '2020-07-17',
		'gameinfo':'https://www.mobygames.com/game/unreal'
	},
	'ugg': {
		'title': 'Untitled Goose Game',
		'source': 'House House',
		'sourceurl': 'https://en.wikipedia.org/wiki/Untitled_Goose_Game',
		'defaulttext': '[done]\u25CF get into the garden[/]\n\u25CF get the groundskeeper wet\n\u25CF steal the groundskeeper\'s keys\n\u25CF make the groundskeeper wear his sun hat\n\u25CF rake in the lake\n\u25CF have a picnic\n    (bring to the picnic blanket : sandwich,\n      apple, pumpkin, carrot, jam, thermos, \n      radio, basket)',
		'platform': 'win32',
		'year': 2019,
		'added': '2019-09-28',
		'updated': '2019-10-01',
		'gameinfo':'https://www.mobygames.com/game/windows/untitled-goose-game'
	},
	'vfa': {
		'title': 'Virtua Fighter Animation',
		'source': 'Aspect Co.',
		'sourceurl': 'https://en.wikipedia.org/wiki/Aspect_Co.',
		'defaulttext': 'You can never trust a ninja.',
		'platform': 'gamegear',
		'year': 1996,
		'added': '2020-07-08',
		'gameinfo':'https://www.mobygames.com/game/virtua-fighter-animation'
	},
	'wsk':{
		'title': 'Wall Street Kid',
		'source': 'SOFEL',
		'sourceurl': 'https://en.wikipedia.org/wiki/SOFEL',
		'defaulttext': "Hello.  I'm Larry, a lawyer\nemployed by your distant\nuncle, Mr. Benedict.  I'm\nsorry to say he's passed \naway.",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/nes/wall-street-kid',
		'added':'2020-04-26',
	},
	'wally': {
		'title': 'Wally Bear and the NO! Gang',
		'source': 'American Game Cartridges',
		'sourceurl': 'https://en.wikipedia.org/wiki/American_Game_Cartridges',
		'defaulttext': 'Taking drugs is stupid,\nToby.',
		'platform':'nes',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/nes/wally-bear-and-the-no-gang',
		'added':'2018-04-05',
	},
	'wargroove': {
		'title': 'Wargroove',
		'source': 'Chucklefish',
		'sourceurl': 'https://en.wikipedia.org/wiki/Chucklefish',
		'platform':'win32',
		'defaulttext': 'Hmph... So many humans. How unpleasant. Still,\nI can avoid most of them.',
		'year':2019,
		'added':'2019-02-04',
		'updated':'2019-02-05',
		'gameinfo':'https://www.mobygames.com/game/wargroove'
	},
	'warioswoods':{
		'title': "Wario's Woods",
		'defaulttext':"what are you\n\ndoin' here?",
		'source': 'Intelligent Systems',
		'sourceurl': 'https://en.wikipedia.org/wiki/Intelligent_Systems',
		'platform':'nes',
		'year':1994,
		'added':'2020-09-13',
		'gameinfo':'https://www.mobygames.com/game/nes/warios-woods'
	},
	'win95': {
		'title': 'Win95 Tips',
		'source': 'Microsoft',
		'sourceurl': 'https://en.wikipedia.org/wiki/Microsoft',
		'platform':'win32',
		'defaulttext': "When you type, you should keep your wrists elevated or use a wristpad to minimize strain.",
		'year':1995,
		'added':'2020-06-02',
		'updated':'2020-07-17',
		'gameinfo':'https://en.wikipedia.org/wiki/Windows_95'
	},
	'win95inst': {
		'title': 'Win95 Installer',
		'source': 'Microsoft',
		'sourceurl': 'https://en.wikipedia.org/wiki/Microsoft',
		'platform':'win32',
		'defaulttext': "Have more fun\nFrom its friendly, intuitive interface to its speedy performance,\nWindows 95 provides you with the most enjoyable computing\nexperience ever.\n\n - Faster video revs up the action in the games you play.\n\n\n - MS-DOS®-based games run better and more reliably.\n\n\n - High-quality multimedia performance will dazzle you.",
		'year':1995,
		'added':'2020-08-24',
		'updated':'2020-08-25',
		'gameinfo':'https://en.wikipedia.org/wiki/Windows_95'
	},
	'wof': {
		'title': 'Wheel of Fortune',
		'source': 'SHAREDATA, Inc',
		'sourceurl': 'http://www.mobygames.com/game/wheel-of-fortune',
		'defaulttext': '  _ _R__P __\n __LL-__SH_RS',
		'play': 'https://archive.org/details/msdos_Wheel_of_Fortune_1987',
		'platform':'dos',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/dos/wheel-of-fortune',
		'added':'2018-06-09',
	},
	'ww':{
		'title': 'Witchy Workshop',
		'source': 'Deerbell',
		'sourceurl': 'https://deerbell.games/witchyworkshop/',
		'defaulttext': 'Books tend to burst info flame\nwhen I read them, so now I buy\nin bulk. So many bad romance\nnovels!',
		'year':2018,
		'platform':'win32',
		'added':'2019-01-02',
		'gameinfo':'https://deerbell.itch.io/witchy-workshop'
	},
	'wh2':{
		'title': 'World Heroes 2',
		'source':'ADK',
		'sourceurl':'https://en.wikipedia.org/wiki/ADK_(company)',
		'defaulttext':'Live my child,so i may\nsmack you around again\nsome day!',
		'platform':'snes',
		'year':1994,
		'gameinfo':'https://www.mobygames.com/game/snes/world-heroes-2',
		'added':'2018-05-14',
		'series':'world heroes'
	},
	'wbm':{
		'title': 'Wrath of the Black Manta',
		'source':'AI',
		'sourceurl':'https://en.wikipedia.org/wiki/Wrath_of_the_Black_Manta',
		'defaulttext':"It seems to be drug\nrelated. You don't use\ndrugs, do you?",
		'platform':'nes',
		'year':1990,
		'gameinfo':'https://www.mobygames.com/game/nes/wrath-of-the-black-manta',
		'added':'2018-04-20',
	},
	'yi':{
		'title': "Yoshi's Island",
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"This paradise is\nYoshi's Island,\nwhere all the\nYoshies live.",
		'platform':'snes',
		'year':1995,
		'gameinfo':'https://www.mobygames.com/game/super-mario-world-2-yoshis-island',
		'added':'2019-02-23',
		'series':'mario'
	},
	'zelda2':{
		'title': 'Zelda II: The Adventure of Link',
		'source':'Nintendo',
		'sourceurl':'https://en.wikipedia.org/wiki/Nintendo',
		'defaulttext':"I AM\nERROR.",
		'platform':'nes',
		'series': 'zelda',
		'year':1987,
		'gameinfo':'https://www.mobygames.com/game/zelda-ii-the-adventure-of-link',
		'added':'2018-04-28',
	},
	'zerowing':{
		'title': 'Zero Wing',
		'source':'Toaplan',
		'sourceurl':'https://en.wikipedia.org/wiki/Toaplan',
		'defaulttext':"Cats: All your base are belong\n      to us.",
		'platform':'genesis',
		'year':1991,
		'gameinfo':'https://www.mobygames.com/game/genesis/zero-wing',
		'added':'2018-02-23',
	},
	'zyuranger':{
		'title': 'Zyuranger',
		'source':'Arc System Works',
		'sourceurl':'https://en.wikipedia.org/wiki/Arc_System_Works',
		'defaulttext':"Oh, Pleprechaun, you've found\nthe perfect Poison Swamp! We\ncan build a creepy prison here\nto lock children in.",
		'platform':'nes',
		'year':1992,
		'gameinfo':'https://www.mobygames.com/game/nes/kyry-sentai-zyuranger',
		'added':'2019-11-20',
		'contributions':[
			{
				'contributor': 'pacnsacdave',
				'url':'https://www.romhacking.net/translations/2604/',
			},
			{
				'contributor': 'Grimm Translations',
				'url':'https://www.romhacking.net/translations/1395/',
			}
		],
		'series':'power rangers'
	},
	'ygodds':{
		'title': 'Yu-Gi-Oh!',
		'source':'Konami',
		'sourceurl':'https://en.wikipedia.org/wiki/Konami',
		'defaulttext':"Welcome to the\nworld of Yu-gi-oh\uD83D\uDCC4",
		'platform':'gameboy',
		'year':1998,
		'gameinfo':'https://www.mobygames.com/game/yu-gi-oh-dark-duel-stories',
		'added':'2020-01-19',
		'updated':'2020-01-20',
		'series':'yu-gi-oh'
	},

}